//! Build script for `xraft-transport`.
//!
//! Generates the tonic gRPC service trait, server, and client for the
//! `RaftService` defined in `proto/raft.proto`. Message types are
//! intentionally NOT regenerated here — the `extern_path` calls below
//! point tonic-build at the prost types already generated by
//! `xraft-core/build.rs` so we have a single canonical wire definition
//! across the workspace.

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let mut config = tonic_build::configure()
        .build_server(true)
        .build_client(true);

    // Reuse all proto message and enum types from xraft-core so we don't
    // duplicate `prost::Message` impls across crates.
    for (proto_name, rust_path) in [
        (
            ".xraft.VoteRequest",
            "::xraft_core::message::proto::VoteRequest",
        ),
        (
            ".xraft.VoteResponse",
            "::xraft_core::message::proto::VoteResponse",
        ),
        (
            ".xraft.PreVoteRequest",
            "::xraft_core::message::proto::PreVoteRequest",
        ),
        (
            ".xraft.PreVoteResponse",
            "::xraft_core::message::proto::PreVoteResponse",
        ),
        (
            ".xraft.FetchRequest",
            "::xraft_core::message::proto::FetchRequest",
        ),
        (
            ".xraft.FetchResponse",
            "::xraft_core::message::proto::FetchResponse",
        ),
        (
            ".xraft.FetchSnapshotRequest",
            "::xraft_core::message::proto::FetchSnapshotRequest",
        ),
        (
            ".xraft.FetchSnapshotChunk",
            "::xraft_core::message::proto::FetchSnapshotChunk",
        ),
        (".xraft.LogEntry", "::xraft_core::message::proto::LogEntry"),
        (
            ".xraft.DivergingEpoch",
            "::xraft_core::message::proto::DivergingEpoch",
        ),
        (".xraft.Endpoint", "::xraft_core::message::proto::Endpoint"),
        (
            ".xraft.VoterRecord",
            "::xraft_core::message::proto::VoterRecord",
        ),
        (".xraft.VoterSet", "::xraft_core::message::proto::VoterSet"),
        (
            ".xraft.SnapshotMetadata",
            "::xraft_core::message::proto::SnapshotMetadata",
        ),
        (
            ".xraft.EntryType",
            "::xraft_core::message::proto::EntryType",
        ),
    ] {
        config = config.extern_path(proto_name, rust_path);
    }

    config.compile_protos(&["../proto/raft.proto"], &["../proto"])?;
    Ok(())
}
